In [ ]:
# python array module
import array as myarray

In [ ]:
#creating an array
arr = myarray.array('i' ,[1,2,3,4,5])
arr1 = myarray.array('d' ,[1.1,2.2,3.3,4.4,5.5])
arr2 = myarray.array('u' ,['a','b','c','d','e'])

#typecodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

print(arr)
print(arr1)
print(arr2)

i
d
u
array('i', [1, 2, 3, 4, 5])
array('d', [1.1, 2.2, 3.3, 4.4, 5.5])
array('u', 'abcde')


In [ ]:
#length of array
print(len(arr))
print(len(arr1))
print(len(arr2))

5
5
5


In [ ]:
for i in range(0,len(arr)):
  print(arr[i],end=" ")
print("\n")
for i in range(0,len(arr1)):
  print(arr1[i],end=" ")
print("\n")
for i in range(0,len(arr2)):
  print(arr2[i],end=" ")

1 2 3 4 5 

1.1 2.2 3.3 4.4 5.5 

a b c d e 

In [ ]:
# For an array of length n , the indexing will start from 0 and end at n-1
#to access the element from array  use index
a = list(range(1,100))
new_array = myarray.array('i',a)

#printing the array
for i in range(0,len(new_array)):
  print(new_array[i],end=" ")
print("\n")

#accessing the element at index "25"
print(new_array[25])

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

26


In [ ]:
# adding elements in an array - insert , append
b= myarray.array('i',[3,4,5,6,7,8,9,10])
for i in range(0,len(b)):
  print(b[i],end=" ")
print(end="\n")
#insert method
b.insert(0,2)
b.insert(0,1)
for i in range(0,len(b)):
  print(b[i],end=" ")

3 4 5 6 7 8 9 10 
1 2 3 4 5 6 7 8 9 10 

In [ ]:
#append method
b.append(11)
for i in range(0,len(b)):
  print(b[i],end=" ")

1 2 3 4 5 6 7 8 9 10 11 

In [ ]:
#updating elements in array
c =myarray.array('i',[1,2,2,4,5])
for i in range(0,len(c)):
  print(c[i],end=" ")
print(end="\n")
#updating the element at index 0
c[2]=30
for i in range(0,len(c)):
  print(c[i],end=" ")
#

1 2 2 4 5 
1 2 30 4 5 

In [ ]:
#deleting elements in an array
c.pop(3)  #here 3 is the index not value 3
print(end="\n")
for i in range(0,len(c)):
  print(c[i],end=" ")
print(end="\n")


1 2 30 5 


In [ ]:
#using the remove() method
c.remove(2)   #2 i s not the index here; it is the value 2
for i in range(0,len(c)):
  print(c[i],end=" ")

1 30 5 

In [ ]:
#slicing in an array
d = list(range(0,100,5))
arr3 = myarray.array('i',d)

#slicing operations
e = arr3[10:20]
for i in range(0,len(e)):
  print(e[i],end=" ")
print("\n")

#negative indexing
f = arr3[9:-10]
for i in range(0,len(f)):
  print(f[i],end=" ")
print("\n")


50 55 60 65 70 75 80 85 90 95 

45 



In [ ]:
for i in range(0,len( arr3)): #array which is used in the above code
  print(i,arr3[i])

0 0
1 5
2 10
3 15
4 20
5 25
6 30
7 35
8 40
9 45
10 50
11 55
12 60
13 65
14 70
15 75
16 80
17 85
18 90
19 95


In [ ]:
g =arr3[::-1]
for i in range(0,len(g)):
  print(g[i],end=" ")

95 90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10 5 0 

In [ ]:
 #searching operations in an array using index()
h = list(range(0,1000000,3))
search = myarray.array('i',h)

 #print 1st 10 elements of the array
for i in range(0,len(search[0:10])):
  print(search[i],end=" ")
print("\n")
#search the number 10005 in the array
index = search.index(10005)
res = search[index]
print(index,res)

0 3 6 9 12 15 18 21 24 27 

3335 10005


In [ ]:
#sorting operations
sort = myarray.array('i',[5,3,4,6,9,7,8])
sorted_array = sort.tolist()
#ascending order
sorted_array.sort()
print(sorted_array)
#descending order
sorted_array.sort(reverse=True)
print(sorted_array)


[3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3]


In [ ]:
#numpy arrays
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print("\n")
zeros = np.zeros((2,2))
ones = np.ones((2,2))
const=np.full((2,2),7)
iden=np.eye(2)
rndom = np.random.random((2,2))
print(zeros)
print("\n")
print(ones)
print("\n")
print(rndom)
print("\n")
print(const)
print("\n")
print(iden)
print("\n")
print(rndom)


[1 2 3 4 5]


[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[0.4935371  0.98708051]
 [0.85883354 0.56779999]]


[[7 7]
 [7 7]]


[[1. 0.]
 [0. 1.]]


[[0.4935371  0.98708051]
 [0.85883354 0.56779999]]


In [ ]:
#1d,2d and 3d numpy arrays
#od array
zerod=np.array(1)
print(zerod)
print("\n")

oned= np.array([1,1])
print(oned)
print("\n")

twod = np.array([[1,2,3,4,5] , [1,2,3,4,5]])
print(twod)
print("\n")

threed = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(threed)
print("\n")
multid = np.array([1,2,3,4,5],ndmin=5)
print(multid)



1


[1 1]


[[1 2 3 4 5]
 [1 2 3 4 5]]


[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


[[[[[1 2 3 4 5]]]]]


In [ ]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)
print(multid.ndim)

1
2
3
5


In [ ]:
#CRUD operations on Numpy Arrays
#reading from a numpy array
sample_array = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0,len(sample_array)):
  print(sample_array[i], end=" ")
print("\n")
#updating elements in a numpy array, we make use of indexing here.
sample_array[9] = 100
print(sample_array)
print("\n")
#deleting elements in a numpy array
sample_array = np.delete(sample_array, 9)
print(sample_array)

1 2 3 4 5 6 7 8 9 10 

[  1   2   3   4   5   6   7   8   9 100]


[1 2 3 4 5 6 7 8 9]


In [ ]:
#searching elements in a numpy array
y =list(range(0,20000,3))
sample_search_array = np.array(y)
#searching the element 15000
res = np.where(sample_search_array==15000)
print(res)
#checking if the returning index is true
print(sample_search_array[5000])


(array([5000]),)
15000


In [ ]:
 #sorting elements in a numpy array
 sample_sort_array  = np.array([1,4,9,2,3,8,7,6])
 #sorting the numpy array using sort()
 z =np.sort(sample_sort_array)
 print(z)

[1 2 3 4 6 7 8 9]
